namespace: lamp-app

# Image settings
images:
  registry: ghcr.io/dolphin-vr/lamp-app-source
  phpTag: "release-e79015d"
  apacheTag: "release-e79015d"
  pullPolicy: Always

# MySQL settings
mysql:
  image: mysql:9.6
  database: "dbmovies"
  storage:
    size: 5Gi
    storageClass: "nfs-client"

# Apache + PHP-FPM (sidecar in the same pod) settings
app:
  replicas: 2
  apache:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  php:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

# Ingress settings
ingress:
  enabled: true
  className: traefik
  host: lamp.ocean.lan
  tls:
    enabled: true
    secretName: lamp-tls-cert
    issuerName: ocean-ca
    certResolver: ""