apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: {{ .Values.namespace }}
  labels:
    app: php
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: php-fpm
  selector:
    app: php
    tier: backend